language: node_js
node_js: 
 - "4.2"
services:
 - mongodb
 - docker
addons:
 hosts:
  - qili.server
  - qili.db
before_script:
 - mkdir test
 - mkdir test/data
 - mkdir test/data/apps
 - sleep 15
 - npm start &
 - sleep 2
after_success:
 - mkdir test/data/qili
 - mkdir test/data/log
 - mkdir test/data/apps
 - cd deploy
 - docker-compose up
 - curl http://locahost