language: node_js
node_js:
 - 14.15.4
services:
 - mongodb
addons:
 hosts:
  - qili.server
  - qili.db
 apt:
  packages:
   - sshpass

before_install:
 - npm install yarn -g

install:
 - yarn install

after_success:
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "./qili.travis.deploy.sh"
