language: node_js
node_js:
 - 6
services:
 - mongodb
addons:
 hosts:
  - qili.server
  - qili.db
 apt:
  packages:
   - sshpass

before_script:
 - mkdir test
 - mkdir test/data
 - mkdir test/data/apps
 - sleep 5
 - npm start &
 - sleep 2


after_success:
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "cd $TARGET_REPOSITORY_PATH && git pull && cd deploy && $TARGET_DOCKER_ENVS docker-compose restart"
