qili.proxy:
 image: "${HUB}nginx:1.9.3"
 ports:
  - "80:80"
  - "443:443"
 links:
  - qili.server
 volumes:
  - "${DATA_ROOT}/data:/data"
  - "${DATA_ROOT}/data/qili/deploy/nginx.conf:/etc/nginx/nginx.conf"

qili.server:
 build: "${DATA_ROOT}/data/qili/deploy/"
 expose:
  - "9080"
  - "9443"
 environment:
  - DOMAIN
  - DB_HOST
  - DB_PORT
  - APPS_ROOT
  - ADMIN_KEY
  - SECRET
  - ROOT
  - ROOT_PASSWORD
  - QINIU_ACCESS_KEY
  - QINIU_SECRET_KEY
  - QINIU_BUCKET
  - QINIU_ACCESS_URL
  - ALI_ACCESS_KEY
  - ALI_SECRET_KEY
  - ALI_SMS_SIGN_NAME=papazai网
  - ALI_SMS_TEMPLATE_RESET
  - ALI_SMS_TEMPLATE_CREATE
  - DEBUG
  - CLOUD_TIMEOUT
  - WECHAT_TOKEN
 links:
  - qili.db
 volumes:
  - "${DATA_ROOT}/data:/data"

qili.db:
 image: "${HUB}mongo:3.1"
 expose:
  - "27017"
 volumes:
  - "${DATA_ROOT}/data/db:/data/db"
 command: --storageEngine=wiredTiger --directoryperdb
