module.exports=function(conf, qili){
    const qiliConfig=require('../../../conf')
    const {apiKey}=qili.app
    const pyCode=
`#auto generated by qili python module
conf=${JSON.stringify({
    api:qiliConfig.api,
    apiKey,
    token: qili.encode({_id:conf.user},{expiresIn:"100y"})
},4)}`
    
    require("fs").writeFileSync("qili-conf.py", pyCode )
    return {
        name:"python",
        init(){
            if(conf?.runPython){
                const apps=Object.keys(qiliConfig.cloud).filter(a=>a!="timeout" && !a.startsWith("__"))
                try{
                    console.info(`runPython: ${apps.join(",")}`)
                    const child=require('child_process')
                        .spawn(
                            "python",
                            [
                                `${__dirname}/run.py`, 
                                //append each app's code root to pythonpath
                                ...apps.map(key=>`${key}:${qiliConfig.cloud[key].code}`)
                            ],
                            {stdio:["inherit", "inherit", "inherit"], killSignal:'SIGINT'}
                        )
                    console.error(`python process id= ${child.pid}`)
                }catch(e){
                    console.error(e)
                }
            }
        }
    }
}