# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deployment

on:
  push:
    branches: [ master ]

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      last: ${{ steps.versions.outputs.last }}
      current: ${{ steps.versions.outputs.current }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: |
          git checkout HEAD^
          echo "::set-output name=last::$(node -p 'require(`./package.json`).version')"
          git checkout master
          echo "::set-output name=current::$(node -p 'require(`./package.json`).version')" 
        id: versions
      - run: echo "${{steps.versions.outputs.last}},${{steps.versions.outputs.current}} "
      

  deploy:
    needs: versions
    if: ${{ needs.versions.outputs.last !=  needs.versions.outputs.current}}
    environment: ALI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn test
    - name: deploy to ali cloud
      uses: lalalic/sshpass-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASS }}
        run: ./qili.travis.deploy.sh
