# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deployment

on:
  push:
    branches: [ master ]

jobs:
  check-version-change:
    runs-on: ubuntu-latest
    outputs:
      lastversion: ${{ steps.verchange.outputs.lastversion }}
      currentversion: ${{ steps.verchange.outputs.currentversion }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: HEAD^1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: lastversion=node -p "require('./package.json').version"
      - id: lastversion
        run: echo ::set-output name=lastversion::$lastversion
      - uses: actions/checkout@v3
      - run: currentversion=node -p "require('./package.json').version"
      - id: currentversion
        run: echo ::set-output name=currentversion::$currentversion
      

  deploy:
    needs: check-version-change
    if: ${{ needs.check-version-change.outputs.lastversion }} != ${{needs.check-version-change.outputs.currentversion}}
    environment: ALI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn test
    - name: deploy to ali cloud
      uses: lalalic/sshpass-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASS }}
        run: ./qili.travis.deploy.sh
